### ISSUE TITLE
About code release

### ISSUE THREAD

**Issue by Colezwhy** [DreamScene-Project/DreamScene#2]
Hi! Thank you for your great work.
And I wonder do you have any plans to release the code soon? I wanted to try it out.
Looking forward to the implementation!

**Comment by Jahnsonblack** [comment]
Thank you for your appreciation of our work. We plan to release the DreamScene code in August. Please look forward to our implementation!

**Comment by Colezwhy** [comment]
> Thank you for your appreciation of our work. We plan to release the DreamScene code in August. Please look forward to our implementation!

Thanks for that!
