### ISSUE TITLE
Failed to run scene sample

### ISSUE THREAD

**Issue by aimyyy** [DreamScene-Project/DreamScene#5]
你好,我在配置完环境后尝试运行场景样例时报出如下错误
Traceback (most recent call last):
  File "/home/micro/DreamScene/main.py", line 24, in <module>
    trainer.train()
NameError: name 'trainer' is not defined

object 样例已经成功跑通了。

**Comment by lclichen** [comment]
Sorry, it has been fixed now.

**Comment by aimyyy** [comment]
Hello, I've got a new problem,Error thrown by the terminal as fllow
 INFO     | training.scene_trainer:train:568 - Start Stage-3
Traceback (most recent call last):
  File "/home/micro/DreamScene/main.py", line 29, in <module>
    trainer.train()
  File "/home/micro/DreamScene/training/scene_trainer.py", line 596, in train
    random.shuffle(self.scene_cams_floor)
AttributeError: 'SceneTrainer' object has no attribute 'scene_cams_floor'. Did you mean: 'scene_cams_record'?

**Comment by lclichen** [comment]
> Hello, I've got a new problem,Error thrown by the terminal as fllow INFO | training.scene_trainer:train:568 - Start Stage-3 Traceback (most recent call last): File "/home/micro/DreamScene/main.py", line 29, in trainer.train() File "/home/micro/DreamScene/training/scene_trainer.py", line 596, in train random.shuffle(self.scene_cams_floor) AttributeError: 'SceneTrainer' object has no attribute 'scene_cams_floor'. Did you mean: 'scene_cams_record'?

Fixed. : )
self.scene_cams_floor is a camera sequence for outdoor scenes, I forgot to remove it from the pipeline of indoor scene generation.
