### ISSUE TITLE
Save entire scene

### ISSUE THREAD

**Issue by tabular7** [DreamScene-Project/DreamScene#6]
Hi, first of all thank you for your awesome work ! 

During the scene generation I noticed, that only the individual objects are saved as a .ply file. 
Is it also possible to save the final scene with all objects inside as a .ply ?

**Comment by lclichen** [comment]
Thank you for your attention! I have added the process of combining the final scene with all objects and saving as a ply file in the dev branch, and will merge it into the main branch after testing.
