### ISSUE TITLE
where is the scene model of .ply type?

### ISSUE THREAD

**Issue by yearnallover** [DreamScene-Project/DreamScene#8]
how can i find the .ply for loading it into Unity

**Comment by lclichen** [comment]
The entire scene's .ply file will be saved to `./experiments/THE EXP NAME FOLDER/scene_checkpoints/scene_final_model.ply`.

Should you plan to import this file into Unity, it may be necessary to modify the relevant code to prevent issues arising from data format incompatibilities.

And the objects in the scene will be saved to `./experiments/THE EXP NAME FOLDER/checkpoints`.

**Comment by yutchina** [comment]
> how can i find the .ply for loading it into Unity

Can you successfully open and render the PLY file?
